master:
  user:
    mail: vipinyedewar14@gmail.com
    name: VIPIN
server:
  port: 9696
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/r_projecthc
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: 9422948998
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    username: vipinyedewar14@gmail.com
